### ISSUE TITLE
DEAP error

### ISSUE THREAD

**Issue by j-woz** [emews/mela#8]

**Comment by j-woz** [comment]
Just tried to run mela/deap and get
```python: code: result = eqpy.output_q_get()
GET
gen     nevals  avg     std     min             max    
0       6       4.56224 3.16836 -2.20061        7.45177
EXCEPTION: Traceback (most recent call last):
  File "/home/wozniak/proj/mela/deap/ext/EQ-Py/eqpy.py", line 39, in run
    self.runnable.run()
  File "/home/wozniak/proj/mela/deap/python/algorithm.py", line 118, in run
    stats=stats, halloffame=hof, verbose=True)
  File "/usb1/wozniak/Public/sfw/anaconda3/lib/python3.6/site-packages/deap/algorithms.py", line 165, in eaSimple
    offspring = toolbox.select(population, len(population))
  File "/usb1/wozniak/Public/sfw/anaconda3/lib/python3.6/site-packages/deap/tools/selection.py", line 67, in selTournament
    aspirants = selRandom(individuals, tournsize)
  File "/usb1/wozniak/Public/sfw/anaconda3/lib/python3.6/site-packages/deap/tools/selection.py", line 24, in selRandom
    return [random.choice(individuals) for i in range(k)]
TypeError: 'float' object cannot be interpreted as an integer
```
I think DEAP changed or broke.

**Comment by j-woz** [comment]
CC @tongshu83

**Comment by ncollier** [comment]
I think I saw something like this recently with the deap I'm using for a different project. I'll try to take a look at the mela deap code as soon as I can.
